version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - appNetwork
    depends_on:
      - db
      - redis

  db:
    image: pgvector/pgvector:pg17
    container_name: who_duck__pgvector-db
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./.dev/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${DATABASE__DB}
      POSTGRES_USER: ${DATABASE__USER}
      POSTGRES_PASSWORD: ${DATABASE__PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - appNetwork

  redis:
    image: docker.io/bitnami/redis:7.4
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS__PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/bitnami/redis/data
    networks:
      - appNetwork


volumes:
  postgres-data: null
  redis-data: null


networks:
  appNetwork:
    driver: bridge
