"""init

Revision ID: 225d14140630
Revises: 
Create Date: 2024-12-22 07:24:17.830278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '225d14140630'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_image_vectors',
    sa.Column('id', sa.String().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_images',
    sa.Column('id', sa.String().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('dir', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('vector_id', sa.String().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('number_of_refs', sa.Integer(), nullable=False),
    sa.Column('last_ref_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vector_id'], ['store_image_vectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_images')
    op.drop_table('store_image_vectors')
    # ### end Alembic commands ###
